services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network
    env_file:
      - ./frontend/.env
    environment:
      - NODE_OPTIONS=--openssl-legacy-provider

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
      - PORT=5000
    volumes:
      - ./backend:/app
    depends_on:
      - mongo
    networks:
      - app-network
    env_file:
      - ./backend/.env

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge

